require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'WebgevMobile' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'WebgevMobileTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  
  IS_CI = ENV['APPCENTER_BUILD_ID']

  if not IS_CI
     use_flipper!()
  end
  
  post_install do |installer|
    flipper_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end

target 'WebgevMobile-tvOS' do
  # Pods for WebgevMobile-tvOS

  target 'WebgevMobile-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
