env:
  browser: true
  es6: true

extends:
  - plugin:import/typescript
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  - plugin:@typescript-eslint/recommended
  - prettier

globals:
  Atomics: readonly
  SharedArrayBuffer: readonly

parser: '@typescript-eslint/parser'

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
  project: './tsconfig.json'

plugins:
  - react
  - import
  - '@typescript-eslint'
  - i18n

settings:
  react:
    version: 'detect'

rules:
  react/prop-types: 'off'
  no-irregular-whitespace: 'error'
  no-useless-escape: 'error'
  i18n/no-russian-character: 'error'
  no-debugger: 'error'

  react/no-set-state: 'error'
  react/no-array-index-key: 'error'
  react/no-danger-with-children: 'error'
  react/no-deprecated: 'warn'
  react/no-redundant-should-component-update: 'error'
  react/no-string-refs: 'error'
  react/no-unescaped-entities: 'warn'
  react/prefer-stateless-function: 'warn'
  react/self-closing-comp: ['error', { component: true, html: true }]
  react/jsx-boolean-value: ['error', 'never']
  react/jsx-curly-brace-presence: ['error', 'never']
  react/jsx-fragments: 'warn'
  react/jsx-key: 'error'
  react/jsx-no-useless-fragment: 'off'
  react/jsx-pascal-case: 'error'
  react/jsx-sort-props: ['error', { shorthandFirst: true, callbacksLast: true }]

  '@typescript-eslint/adjacent-overload-signatures': 'error'
  '@typescript-eslint/array-type': ['error', { default:"array-simple" }]
  '@typescript-eslint/ban-ts-comment': 'off'
  '@typescript-eslint/ban-types': 'error'
  '@typescript-eslint/consistent-type-definitions': 'error'
  '@typescript-eslint/member-ordering': 'warn'
  '@typescript-eslint/no-empty-interface': 'off'
  '@typescript-eslint/no-explicit-any': 'error'
  '@typescript-eslint/no-extra-non-null-assertion': 'error'
  '@typescript-eslint/no-floating-promises': ['error', { ignoreVoid: true }]
  '@typescript-eslint/no-for-in-array': 'error'
  '@typescript-eslint/no-misused-new': 'error'
  '@typescript-eslint/no-misused-promises': 'error'
  '@typescript-eslint/no-non-null-asserted-optional-chain': 'error'
  '@typescript-eslint/no-require-imports': 'off'
  '@typescript-eslint/no-throw-literal': 'error'
  '@typescript-eslint/no-unnecessary-boolean-literal-compare': 'error'
  '@typescript-eslint/no-unnecessary-type-arguments': 'error'
  '@typescript-eslint/prefer-as-const': 'error'
  '@typescript-eslint/prefer-for-of': 'error'
  '@typescript-eslint/prefer-includes': 'error'
  '@typescript-eslint/no-extraneous-class': 'error'
  '@typescript-eslint/no-this-alias': 'error'
  '@typescript-eslint/prefer-optional-chain': 'error'
  '@typescript-eslint/prefer-regexp-exec': 'warn'
  '@typescript-eslint/prefer-string-starts-ends-with': 'error'
  '@typescript-eslint/promise-function-async': 'error'
  '@typescript-eslint/switch-exhaustiveness-check': 'error'
  '@typescript-eslint/restrict-plus-operands': 'warn'
  '@typescript-eslint/explicit-function-return-type': 'off'
  '@typescript-eslint/no-use-before-define': 'off'

  '@typescript-eslint/no-var-requires': 'off'
  '@typescript-eslint/ban-ts-ignore': 'off'
  '@typescript-eslint/camelcase': 'off'

  import/no-cycle: 'error'
  import/no-useless-path-segments: 'error'
  import/no-unused-modules: 'error'
  import/order:
    [
      'error',
      {
        alphabetize: { order: 'asc' },
        'newlines-between': 'always',
        groups: ['builtin', 'external', 'internal', 'parent', 'sibling', 'index', 'unknown'],
        pathGroups: [{ pattern: '~/**', group: 'internal' }, { pattern: './**', group: 'sibling' }],
      },
    ]

  react/no-children-prop: 0
  no-magic-numbers: 0
  react/display-name: 0
